---
title: "student-success-analysis"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(rlang)
library(tidyverse)
message("Your current working directory is: ", getwd())
```


## Data loading and getting the feeling of the dataset

```{r}
students_org <- readxl::read_excel("student_data.xlsx")

# 370 rows, 39 columns
dim(students_org)

# Show column names
names(students_org)
```
```{r}
# Show first few rows
head(students_org)
```


```{r}
# Show details for each column
summary(students_org)
```


```{r}
# Check the class of the column. "numeric", "character"...
sapply(students_org,class)
```

```{r}

# Let's check if any columns exceed the maximum or minumum values specified in the pdf
# This makes sense only for numerical values

colMax <- students_org %>% select(where(is.numeric)) %>% sapply(., max, na.rm = TRUE)
colMax

# Every column has normal maximum value
```




```{r}
# Are there any na values?
students_org %>% filter(is.na(.))
sum(apply(students_org,2,is.nan))
students_org %>% filter(is.null(.))

# Drop these values just in case they show up with another dataset
# We will continue using "student" variable
students <- students_org %>% filter_all(all_vars(!is.na(.) & !is.nan(.) & !is.null(.)))
```
```{r}
students$average_grade <- (students$G3_mat + students$G3_por)/2

fit.studytime = lm(average_grade~studytime,data=students)
plot(students$studytime,students$average_grade)
lines(students$studytime,fit.studytime$fitted.values,col='red')

#Pearsonov korelacijski koeficijent
cor(students$studytime,students$average_grade)

cor.test(students$studytime,students$average_grade)

summary(fit.studytime)

#procjena modela s dummy varijablama
require(fastDummies)
students.d = dummy_cols(students,select_columns='studytime')

#procjena modela s dummy varijablama
fit.multi.d = lm(average_grade ~ studytime_1 + studytime_2, students.d)
summary(fit.multi.d)
```


